### PR TITLE
upgrade ioredis and dev dependencies

### PR DESCRIPTION
**Pull request by briangough**
Upgrade ioredis to latest version, v4.27.1. 

See https://github.com/luin/ioredis/blob/master/Changelog.md#4271-2021-04-24

The changes from 4.17.3 seem to be minor ones.

Also upgrade devDependencies.

### CODE REVIEW

**Review by das7pad — COMMENTED** [review]
The ioredis upgrade LGTM. Can you bring back the package-lock to allow reproducible testing?

I also went though the diff upstream and nothing stands out for standalone mode. The forced-disconnection of broken connections could help us in fail-over situations. There is a bit of queuing going on for the cluster mode when no slot-cache is available.
https://github.com/luin/ioredis/compare/v4.17.3...master

**Comment by briangough** [comment]
> The ioredis upgrade LGTM. Can you bring back the package-lock to allow reproducible testing?

Done

**Review by das7pad — APPROVED** [review]
Thanks for bringing back the package-lock!

**Comment by briangough** [comment]
Links for reference: 
- https://stackoverflow.com/questions/44546718/should-package-lock-json-also-be-published
- https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json/

**Pull request merged**
